/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import clases.*;

/**
 *
 * @author ACER
 */
public class BorrarDocEspecifico extends javax.swing.JFrame {

    private String path;
    private Lista usuarios;
    private usuariosSistema uc;
    private Bin_Heap bin;
    private TimerUI ti;
    
    
    /**
     * Creates new form BorrarDocEspecifico
     */
    public BorrarDocEspecifico() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloBorrarDocEspecifico = new javax.swing.JLabel();
        VolverBorrarDocEspecificoBut = new javax.swing.JButton();
        NombreUsusarioLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NombreUsuarioText = new javax.swing.JTextField();
        NombreDocumentoText = new javax.swing.JTextField();
        FondoDocEspecificoFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 100, -1, -1));

        TituloBorrarDocEspecifico.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TituloBorrarDocEspecifico.setForeground(new java.awt.Color(255, 255, 255));
        TituloBorrarDocEspecifico.setText("Borrar documento especifico");
        getContentPane().add(TituloBorrarDocEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 70));

        VolverBorrarDocEspecificoBut.setBackground(new java.awt.Color(0, 0, 0));
        VolverBorrarDocEspecificoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VolverBorrarDocEspecificoBut.setForeground(new java.awt.Color(255, 255, 255));
        VolverBorrarDocEspecificoBut.setText("Volver");
        VolverBorrarDocEspecificoBut.setBorderPainted(false);
        VolverBorrarDocEspecificoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBorrarDocEspecificoButActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBorrarDocEspecificoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        NombreUsusarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NombreUsusarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        NombreUsusarioLabel.setText("Nombre del usuario:");
        getContentPane().add(NombreUsusarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del documento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Borrar");
        jButton1.setBorderPainted(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        NombreUsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioTextActionPerformed(evt);
            }
        });
        getContentPane().add(NombreUsuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 250, 30));
        getContentPane().add(NombreDocumentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 250, 30));

        FondoDocEspecificoFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/FondoBorrarDocEspecifico.png"))); // NOI18N
        getContentPane().add(FondoDocEspecificoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBorrarDocEspecificoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBorrarDocEspecificoButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Impresora ventana = new Impresora();
        ventana.setVisible(true);
    }//GEN-LAST:event_VolverBorrarDocEspecificoButActionPerformed

    private void NombreUsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarDocEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarDocEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarDocEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarDocEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarDocEspecifico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoDocEspecificoFondo;
    private javax.swing.JTextField NombreDocumentoText;
    private javax.swing.JTextField NombreUsuarioText;
    private javax.swing.JLabel NombreUsusarioLabel;
    private javax.swing.JLabel TituloBorrarDocEspecifico;
    private javax.swing.JButton VolverBorrarDocEspecificoBut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Lista getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(Lista usuarios) {
        this.usuarios = usuarios;
    }

    public usuariosSistema getUc() {
        return uc;
    }

    public void setUc(usuariosSistema uc) {
        this.uc = uc;
    }

    public Bin_Heap getBin() {
        return bin;
    }

    public void setBin(Bin_Heap bin) {
        this.bin = bin;
    }

    public TimerUI getTi() {
        return ti;
    }

    public void setTi(TimerUI ti) {
        this.ti = ti;
    }

    

    




}
