/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import clases.Documento;
import clases.Lista;
import clases.Nodo;
import clases.Usuario;
import clases.Bin_Heap;


/**
 *
 * @author ACER
 */
public class BorrarDocumento extends javax.swing.JFrame {
    private String path;
    private Lista usuarios;
    private usuariosSistema uc;
    private Bin_Heap bin;
    private TimerUI ti;
    /**
     * Creates new form BorrarUsuario
     */
    public BorrarDocumento() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloBorrarDocumento = new javax.swing.JLabel();
        VolverBorrarDocumentoBut = new javax.swing.JButton();
        BorrarLabel = new javax.swing.JLabel();
        BorrarText = new javax.swing.JTextField();
        BorrarBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        FondoBorrarDocumento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 136, -1, -1));

        TituloBorrarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloBorrarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        TituloBorrarDocumento.setText("Borrar documento");
        getContentPane().add(TituloBorrarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        VolverBorrarDocumentoBut.setBackground(new java.awt.Color(0, 0, 0));
        VolverBorrarDocumentoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VolverBorrarDocumentoBut.setForeground(new java.awt.Color(255, 255, 255));
        VolverBorrarDocumentoBut.setText("Volver");
        VolverBorrarDocumentoBut.setBorderPainted(false);
        VolverBorrarDocumentoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBorrarDocumentoButActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBorrarDocumentoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        BorrarLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BorrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        BorrarLabel.setText("Documento:");
        getContentPane().add(BorrarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        BorrarText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(BorrarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 270, 30));

        BorrarBut.setBackground(new java.awt.Color(0, 0, 0));
        BorrarBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BorrarBut.setForeground(new java.awt.Color(255, 255, 255));
        BorrarBut.setText("Aceptar");
        BorrarBut.setBorderPainted(false);
        BorrarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarButActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, -1));

        FondoBorrarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/FondoBorrarDocumento.png"))); // NOI18N
        getContentPane().add(FondoBorrarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBorrarDocumentoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBorrarDocumentoButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ModificarDocumento ventana = new ModificarDocumento();
        ventana.setPath(getPath());
        ventana.setUsuarios(getUsuarios());
        ventana.setUc(getUc());
        ventana.setBin(getBin());
        ventana.setTi(getTi());
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBorrarDocumentoButActionPerformed

    private void BorrarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButActionPerformed
        String usuario = user.getText();
        String nombre = BorrarText.getText();
        Nodo pAux = getUsuarios().getHead();
        int cont = 0;
        while (pAux!=null){
            if ((((Usuario) pAux.getElement()).getNombre()).equalsIgnoreCase(usuario)){
                Nodo pAux2 = ((Usuario) pAux.getElement()).getDocumentos().getHead();
                while(pAux2!=null){
                    if(((Documento) pAux2.getElement()).getNombre().equalsIgnoreCase(nombre)){
                        break;
                    }
                    cont++;
                    pAux2=pAux2.getNext();
                }
                ((Usuario) pAux.getElement()).getDocumentos().deleteAtIndex(cont);
            }
            pAux=pAux.getNext();
        }
    }//GEN-LAST:event_BorrarButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarBut;
    private javax.swing.JLabel BorrarLabel;
    private javax.swing.JTextField BorrarText;
    private javax.swing.JLabel FondoBorrarDocumento;
    private javax.swing.JLabel TituloBorrarDocumento;
    private javax.swing.JButton VolverBorrarDocumentoBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the path
     */
    public String getPath() {
        return path;
    }

    /**
     * @param path the path to set
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * @return the usuarios
     */
    public Lista getUsuarios() {
        return usuarios;
    }

    /**
     * @param usuarios the usuarios to set
     */
    public void setUsuarios(Lista usuarios) {
        this.usuarios = usuarios;
    }

    public usuariosSistema getUc() {
        return uc;
    }

    public void setUc(usuariosSistema uc) {
        this.uc = uc;
    }

    public Bin_Heap getBin() {
        return bin;
    }

    public void setBin(Bin_Heap bin) {
        this.bin = bin;
    }

    public TimerUI getTi() {
        return ti;
    }

    public void setTi(TimerUI ti) {
        this.ti = ti;
    }

    
    
    
    
    
    
}
