/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import clases.csv;

/**
 *
 * @author UsuarioDeWindows
 */
public class CargarArchivo extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public CargarArchivo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargarArchivoBut = new javax.swing.JButton();
        TituloProyecto = new javax.swing.JLabel();
        Fondocargar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(582, 496));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargarArchivoBut.setBackground(new java.awt.Color(0, 0, 0));
        CargarArchivoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CargarArchivoBut.setForeground(new java.awt.Color(255, 255, 255));
        CargarArchivoBut.setText("Cargar archivo");
        CargarArchivoBut.setBorderPainted(false);
        CargarArchivoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoButActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, 80));

        TituloProyecto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TituloProyecto.setForeground(new java.awt.Color(255, 255, 255));
        TituloProyecto.setText("Proyecto2: Cola de Prioridad");
        getContentPane().add(TituloProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Fondocargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/FondoCargarArchivo.png"))); // NOI18N
        getContentPane().add(Fondocargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoButActionPerformed
        this.setVisible(false);
        SistemaOperativo ventanasistema = new SistemaOperativo();
        ventanasistema.setVisible(true);

//        csv c = new csv();
//        c.leer(c.Seleccionar()).print();
        
    }//GEN-LAST:event_CargarArchivoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArchivoBut;
    private javax.swing.JLabel Fondocargar;
    private javax.swing.JLabel TituloProyecto;
    // End of variables declaration//GEN-END:variables
}
