/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author ACER
 */
public class ModificarDocumento extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUsuario
     */
    public ModificarDocumento() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloModificarDocumento = new javax.swing.JLabel();
        VolverModificarDocumentoBut = new javax.swing.JButton();
        AgregarDocumentoBut = new javax.swing.JButton();
        BorrarDocumentoBut = new javax.swing.JButton();
        FondoModificarDocumento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 147, -1, -1));

        TituloModificarDocumento.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloModificarDocumento.setForeground(new java.awt.Color(255, 255, 255));
        TituloModificarDocumento.setText("Que desea hacer");
        getContentPane().add(TituloModificarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        VolverModificarDocumentoBut.setBackground(new java.awt.Color(0, 0, 0));
        VolverModificarDocumentoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VolverModificarDocumentoBut.setForeground(new java.awt.Color(255, 255, 255));
        VolverModificarDocumentoBut.setText("Volver");
        VolverModificarDocumentoBut.setBorderPainted(false);
        VolverModificarDocumentoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverModificarDocumentoButActionPerformed(evt);
            }
        });
        getContentPane().add(VolverModificarDocumentoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        AgregarDocumentoBut.setBackground(new java.awt.Color(0, 0, 0));
        AgregarDocumentoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AgregarDocumentoBut.setForeground(new java.awt.Color(255, 255, 255));
        AgregarDocumentoBut.setText("Agregar Documento");
        AgregarDocumentoBut.setBorderPainted(false);
        AgregarDocumentoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDocumentoButActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarDocumentoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, 50));

        BorrarDocumentoBut.setBackground(new java.awt.Color(0, 0, 0));
        BorrarDocumentoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BorrarDocumentoBut.setForeground(new java.awt.Color(255, 255, 255));
        BorrarDocumentoBut.setText("Borrar Documento");
        BorrarDocumentoBut.setBorderPainted(false);
        BorrarDocumentoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarDocumentoButActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarDocumentoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 210, 50));

        FondoModificarDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/FondoModificarDocumento.png"))); // NOI18N
        getContentPane().add(FondoModificarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverModificarDocumentoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverModificarDocumentoButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SistemaOperativo ventanasistema = new SistemaOperativo();
        ventanasistema.setVisible(true);
    }//GEN-LAST:event_VolverModificarDocumentoButActionPerformed

    private void AgregarDocumentoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDocumentoButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AgregarDocumento ventana = new AgregarDocumento();
        ventana.setVisible(true);
    }//GEN-LAST:event_AgregarDocumentoButActionPerformed

    private void BorrarDocumentoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarDocumentoButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BorrarDocumento ventana = new BorrarDocumento();
        ventana.setVisible(true);

    }//GEN-LAST:event_BorrarDocumentoButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDocumentoBut;
    private javax.swing.JButton BorrarDocumentoBut;
    private javax.swing.JLabel FondoModificarDocumento;
    private javax.swing.JLabel TituloModificarDocumento;
    private javax.swing.JButton VolverModificarDocumentoBut;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
