/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author ACER
 */
public class SistemaOperativo extends javax.swing.JFrame {

    /**
     * Creates new form SistemaOperativo
     */
    public SistemaOperativo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloSistemaOperativo = new javax.swing.JLabel();
        VolverSistemaOperativoBut = new javax.swing.JButton();
        ModificarUsuarioBut = new javax.swing.JButton();
        ModificarDocumentosBut = new javax.swing.JButton();
        ImpresoraBut = new javax.swing.JButton();
        FondoSIstemaOperativo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 116, -1, -1));

        TituloSistemaOperativo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloSistemaOperativo.setText("Que desea hacer");
        getContentPane().add(TituloSistemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        VolverSistemaOperativoBut.setBackground(new java.awt.Color(0, 0, 0));
        VolverSistemaOperativoBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VolverSistemaOperativoBut.setText("Volver");
        VolverSistemaOperativoBut.setBorderPainted(false);
        VolverSistemaOperativoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverSistemaOperativoButActionPerformed(evt);
            }
        });
        getContentPane().add(VolverSistemaOperativoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        ModificarUsuarioBut.setBackground(new java.awt.Color(0, 0, 0));
        ModificarUsuarioBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarUsuarioBut.setText("Modificar usuario");
        ModificarUsuarioBut.setBorderPainted(false);
        ModificarUsuarioBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioButActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarUsuarioBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 240, 60));

        ModificarDocumentosBut.setBackground(new java.awt.Color(0, 0, 0));
        ModificarDocumentosBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarDocumentosBut.setText("Modificar documento");
        ModificarDocumentosBut.setBorderPainted(false);
        getContentPane().add(ModificarDocumentosBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 242, 240, 60));

        ImpresoraBut.setBackground(new java.awt.Color(0, 0, 0));
        ImpresoraBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ImpresoraBut.setText("Impresora");
        ImpresoraBut.setBorderPainted(false);
        getContentPane().add(ImpresoraBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 240, 60));

        FondoSIstemaOperativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/FondoSistemaOperativo.png"))); // NOI18N
        getContentPane().add(FondoSIstemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverSistemaOperativoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverSistemaOperativoButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverSistemaOperativoButActionPerformed

    private void ModificarUsuarioButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarUsuarioButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaOperativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoSIstemaOperativo;
    private javax.swing.JButton ImpresoraBut;
    private javax.swing.JButton ModificarDocumentosBut;
    private javax.swing.JButton ModificarUsuarioBut;
    private javax.swing.JLabel TituloSistemaOperativo;
    private javax.swing.JButton VolverSistemaOperativoBut;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
